#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "$HOME/.Xmodmap"

#Set proper resolution
"$HOME/.screenlayout/std.sh"



# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &


#conky
firefox &
pidgin &
terminator -m&
skype &
terminator -T irssi -e irssi &
conky > /dev/null &















# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#exec fluxbox
# or if you want to keep a log:
exec fluxbox -log "$HOME/.fluxbox/log"
